### PR TITLE
Add ergometer-space.org

### PR DESCRIPTION
**Pull request by tijmenvangulik**
I could row using webhid in canary in ergometer-space.org. So I added it as an real world application.

### CODE REVIEW

**Comment by robatwilliams** [comment]
Thanks for the PR. I've made some tweaks as you'll see above - do they look ok?

I see that you developed this over the past few years to try out new web technologies, and the ErgometerJS source code is on GitHub. As such it's probably a better fit for the Demos section, with a link to the source code.

**Comment by tijmenvangulik** [comment]
Thanks for adding the website. To clarify things: Only the internal ergometer driver souce code is on github. Ergometer space is much bigger and a real world ergometer app with a lot of features and not just a demo. Ergometer space is not On GitHub 

Tijmen

**Comment by robatwilliams** [comment]
Yes, I had seen that it's a separate library.

I see a lot of work has gone into the app, and you've been posting about it on some forums. Does anyone use it?

**Comment by tijmenvangulik** [comment]
I am not sure how much it is used currently. I removed the google counters because of privacy laws. I know that the android app is used (about 100 installations for some years). I hope it wil be used more since I have added usb this week (most ergometers do not have a PM5 which uses bluetooth ) The app also needs some more UX to make people use it. With some more effort I expect it to grow..

Tijmen

**Comment by robatwilliams** [comment]
Ok. I was debating with myself what counts as a real app, this list is quite empty at the moment so I don't need to be too strict. I see the functionality is there and can be used ([YouTube video](https://www.youtube.com/watch?v=a-he4dK2QCs) from 2015), so I'm going to accept it regardless of user numbers or UX quality.

It's a relevant usage of WebHID, regardless of if HID is done over USB or Bluetooth.

Thanks for submitting.

**Pull request merged**
