### PR TITLE
added blink1-webhid demo link

### PR DESCRIPTION
**Pull request by todbot**
Hi!
Thanks for making this list and making some demos for me to crib from.  I made `blink1-webhid` and they work great on Mac & Windows.

### CODE REVIEW

**Comment by robatwilliams** [comment]
Thanks for making and for submitting.

**Comment by tijmenvangulik** [comment]
﻿Also thank you for the blink project , I used the electron demo package configuration to get the right config to get usb working in desktop version. I also see that you do not have a Cordova implementation for blink. I published a usb hid driver for Cordova recently. 

Tijmen
Ps there is no team it is just a pet project of mine

**Comment by tijmenvangulik** [comment]
I come back later on your offer. I checkout blink first, thanks

Tijmen

**Comment by tijmenvangulik** [comment]
Thanks for the offer. I just looked blink1, looks something definitely worth experimenting with it.  How much will it cost me?

Tijmen

**Comment by robatwilliams** [comment]
Tijmen, I'm not sure the offer extended to everyone. The blink(1) website is at https://blink1.thingm.com/, also linked from this very awesome-list.

**Pull request merged**
